### ISSUE TITLE
Send certificate link in course completed email

### ISSUE THREAD

**Issue by RiaanKnoetze** [woocommerce/sensei-certificates#80]
Link to ticket: https://woothemes.zendesk.com/agent/tickets/370475

When a learner completes a course, the link to their certificate should be added to the "Course Completed" email sent to the learner.

**Comment by richardmtl** [comment]
Also requested in 410437-zd-woothemes

**Comment by jeherve** [comment]
Also requested in 417051-zd-woothemes

**Comment by PederSongedal** [comment]
A link is good start. But what my users really want is a PDF in the email.

**Comment by MendesSP** [comment]
Definitely a must

**Comment by BusinessBloomer** [comment]
Yes, badly needed :)

**Comment by BusinessBloomer** [comment]
Folks, I've started working on this. I wonder if anyone here can solve my problems:

1. I want to create an email with header/footer by Sensei, and not a plain text one
2. I want to email the link to the Cert, and not the Cuorse completed page

`add_action( 'sensei_user_course_end', 'email_certificate_when_available', 50, 2);

function email_certificate_when_available( $user_id, $course_id ) {
$certificate_template_id = get_post_meta( $course_id, '_course_certificate_template', true );
if( $certificate_template_id ) {

/* PROBLEM NO1: trying to get the Cert link instead of Courses Page link!
** Not sure here how to call the private function get_certificate_url() inside
** WooThemes_Sensei_Certificates class
*/

//$cert = new WooThemes_Sensei_Certificates();
//$certificate_url = $cert->get_certificate_url( $course_id, $user_id );

$certificate_url = site_url() . '/my-courses/#completed-courses';
}
        $to = 'test@test.test';
	$subject = 'Congrats, Your Cert is Available for Download!';
	$message = "Hello there\r\n";
	$message .= "Your certificate is now available for download: ";
	$message .= $certificate_url;
        
        /* PROBLEM NO2: trying to get the Sensei email header/footer! */
	wp_mail($to, $subject, $message );
}
`

Maybe if anyone contributes to this we can build a simple snippet!

R

**Comment by PederSongedal** [comment]
If we can send the diploma to the teacher, at the same time as to the student it while make my job easier.

**Comment by BusinessBloomer** [comment]
@PederSongedal I updated the snippet, now this will display Certificate info to both student and teacher on the "Completed Course" email.

I'm still struggling to get the direct link to the Certificate via the function:

`private function get_certificate_url( $course_id, $user_id )`

which can be found under class-woothemes-sensei-certificates.php on line 819. Can anyone help?

**Comment by annezazu** [comment]
requested here: 569025-zd-woothemes

**Comment by gaurav1984** [comment]
Also requested in 604211-zd-woothemes

**Comment by donnapep** [comment]
The email would be adjusted to include a "View your certificate" link look at the end of the email:

![screen shot 2019-02-26 at 5 45 54 am](https://user-images.githubusercontent.com/1190420/53407319-ecf08800-3989-11e9-9a58-a7aa176b7c24.jpg)

**Comment by avnibania** [comment]
> A link is good start. But what my users really want is a PDF in the email.

Hey, did you find any solution for it?
